### ISSUE TITLE
improve legend

### ISSUE THREAD

**Issue by zackarno** [OCHA-DAP/ds-nga-flood-monitoring#2]
- make legend text bigger
- move legend to right of map, add transparent white background, remove Cameroon label

**Comment by zackarno** [comment]
I adjusted legend and sent test emails with `{blastula}`. The legend sizes appeared good in test emails, but when running on GHA they have changed back to being too small.

Can see the changes implemented here:
https://github.com/OCHA-DAP/ds-nga-flood-monitoring/pull/4#issue-1850490291

Unclear how this is happening.

**Comment by caldwellst** [comment]
I believe it's because you are not adding the map to the email with a specified size. I would just wrap `m_basins_plot` with `add_ggplots_custom()` until you find a working size. This should keep it consistent between machines, I believe. I tried to do and test, but don't actually have the JSON so can get the auth JSON and test when you're back online if you want.

**Comment by zackarno** [comment]
hmm `add_ggplots_custom()`  doesn't work because `add_ggplot()` relies on `ggsave()` . Interestingly if I convert the tmap object to a `grob` with `tmap_grob()` it does work, but creates alot of white space above the plot.

Because of the reliance on `ggsave()` I had previously made `add_tmap()` and `add_tmap_custom()` for some DRC cholera emails, but they ended up making the maps a bit blurry so got better outputs just plotting directly with tmap. Nonetheless, those `add_tmap/tmap_custom()` funcs are already in the `email_utils.R` file so i will play with them a bit more. I will share the JSON info as well.

**Comment by caldwellst** [comment]
Aaah I see, yeah didn't realise `tmap` is a separate system. White space can be a common issue with geographic coordinate plots in `{ggplot2}`, but there are lots of [easy solutions](https://stackoverflow.com/questions/35346111/r-ggplot-remove-white-margins-in-ggsave-ggplot). However, makes sense to have the separate `add_tmap()` functionality so will review the code!
